### ISSUE TITLE
会加RabbitMQ和单聊/私有群聊么

### ISSUE THREAD

**Issue by ghost** [link1st/gowebsocket#10]
会加RabbitMQ和单聊么,因为现在只有公共聊天的,但是对于私有群聊以及单聊的逻辑不是很清楚,请问下是否会加呢?想请教一下!

**Comment by link1st** [comment]
这个项目主要是想实现一个长连接系统，实现比较基础的功能(保持一个长连接)，供别的系统接入(IM/任务完成消息推送等)

在项目演示的时候选用的是IM系统把所有人拉到一个群里面，可以很轻松的借助这个长连接系统实现群聊功能~

关于更多的IM的细节((私有群聊以及单聊))实现暂时没有这个计划，RabbitMQ 是消息队列目前没有这个需求
