### ISSUE TITLE
找不到配置文件

### ISSUE THREAD

**Issue by littlecurl** [link1st/gowebsocket#11]
完整报错如下：
panic: Fatal error config file: Config File "config/app" Not Found in "[D:\\Workspace\\Go\\src\\github.com\\link1st\\gowebsocket]" 

goroutine 1 [running]:
main.initConfig()
	D:/Workspace/Go/src/github.com/link1st/gowebsocket/main.go:72 +0x29f
main.main()
	D:/Workspace/Go/src/github.com/link1st/gowebsocket/main.go:27 +0x2d

为了跑这个项目，我go get了 14个小时，终于get完了，结果找不到配置文件。

你们都是怎么跑起来的呀？

**Comment by littlecurl** [comment]
还有就是，前辈有QQ群之类的吗？Github交流略微低效了一点。

**Comment by link1st** [comment]
github 上面有 issues 我看到都会第一时间回复的

项目 clone 比较慢的问题，是为了避免二次下载依赖，本项目都是将依赖放在项目的 **vendor** 目录中了，所以项目比较大了一些(13.7 MB)

- 找不到配置文件问题，需要进去 **config** 目录重命名一下配置文件，还需要配置 redis

```
mv app.yaml.example app.yaml
```

[4.3 项目启动](https://github.com/link1st/gowebsocket#43-%E9%A1%B9%E7%9B%AE%E5%90%AF%E5%8A%A8) 项目启动的步骤，体验项目可以看这里

**Comment by littlecurl** [comment]
我重命名了一下，果真可以运行了，多谢前辈指点。
你可以贴个支付宝、微信二维码什么的，给你转五块十块的，我想表示一下语言之外的感谢。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Link"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月21日(星期六) 晚上7:19
收件人:&nbsp;"link1st/gowebsocket"<gowebsocket@noreply.github.com&gt;;
抄送:&nbsp;"424171723"<littlecurl@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [link1st/gowebsocket] 找不到配置文件 (#11)




github 上面有 issues 我看到都会第一时间回复的
 
项目 clone 比较慢的问题，是为了避免二次下载依赖，本项目都是将依赖放在项目的 vendor 目录中了，所以项目比较大了一些(12.6M)
 
4.3 项目启动 项目启动的步骤，体验项目可以看这里
  
找不到配置文件问题，需要进去 config 目录重命名一下配置文件，还需要配置 redis
  mv app.yaml.example app.yaml

**Comment by link1st** [comment]
技术只有分享才可以让更多的人使用，共同学习共同进步~
