### ISSUE TITLE
CentOS7云服务器重启导致 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by littlecurl** [link1st/gowebsocket#12]
请教前辈一个问题：

前提说明：
本地和云端都没有使用Nginx，仅仅是单纯的运行。

问题如下：
本地Windows环境IDEA跑这个项目，多次重启都没有问题，聊天页面可以进行聊天；
把项目放到阿里云CentOS 7 服务器上，第一次启动也没问题，聊天页面可以进行聊天。
但是，一旦重新启动，即Ctrl+C停止服务后，再次go run main.go，聊天页面就无法访问。

前端Http状态码返回503
后端报错如下：

```shell
2019/12/25 14:29:23 http: panic serving 114.64.253.3:3257: runtime error: invalid memory address or nil pointer dereference
goroutine 171 [running]:
net/http.(*conn).serve.func1(0xc00018e8c0)
	/usr/lib/golang/src/net/http/server.go:1767 +0x139
panic(0xc26460, 0x13bd940)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
github.com/gin-gonic/gin.(*Context).Next(0xc00009cbb0)
	/home/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x36
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000141400, 0xc00009cbb0)
	/home/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b2
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000141400, 0xe562e0, 0xc00017e380, 0xc0000d7600)
	/home/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x134
net/http.serverHandler.ServeHTTP(0xc00017e1c0, 0xe562e0, 0xc00017e380, 0xc0000d7600)
	/usr/lib/golang/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00018e8c0, 0xe58920, 0xc000288700)
	/usr/lib/golang/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2927 +0x38e
```
如果把项目文件夹从阿里云服务器删除，然后重新上传，再次启动，依然是第一次启动可以访问通，再次重启无法访问，一样的报错。

云端启停都是root用户。

我根据 `runtime error: invalid memory address or nil pointer dereference` 去网上搜索：

网上有些人说是代码的问题，但是，第一次运行的时候，确实是能跑通的。

还有人说是centOS7 防火墙问题，我检测了一下，防火墙是关闭状态。

前辈是否也遇到过同样的问题呢？

**Comment by link1st** [comment]
目前没有遇到这个问题，我的项目也是放在阿里云上运行的，目前没有出现问题

是否是在第二次启动的时候，端口被占用了？ 试试第二次启动的时候重新设置一个端口查看是否可以正常访问

**Comment by link1st** [comment]
这个错误看着像是一个http接口请求到了服务端的时候才报错，是否是这个接口 有问题呢？

[错误示例](https://github.com/gin-gonic/gin/issues/1303) 是否遇到和他一样的问题

**Comment by littlecurl** [comment]
先说明一下，问题解决了，感谢前辈的回复提醒了我。
----------------
经过了近20小时的排查，终于发现问题所在了。
果然是我的代码的问题。
前辈提到你的代码重启没问题，我就在想，我是fork你的代码，**咱俩代码之间到底有哪些不同**。
我主要做了两点改变：
1、数据入库（使用Go的标准库）
2、日志写入文件并切割（从网上随便找的一个中间件，完整源码放到最下面了）
问题就出现在这第 2 点上
我先是注释掉了路由默认的生成方式，然后使用gin.New()，
再使用自定义的log中间件，这是造成Bug的入口
```go
	//router := gin.Default()

	router := gin.New()
	//使用自定义日志框架
	router.Use(middleware.LoggerToFile(), gin.Recovery())
```
在LoggerToFile()方法里，写入文件的时候
```go
	// 写入文件
        // 好像按照他下面配置的打开方式，如果文件存在，就会打开失败，但是，我很困惑的是，第一次启动是可以运行的：）我再研究研究吧 
	src, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, os.ModeAppend)
	if err != nil {
		// 如果创建失败，尝试手动创建一下
		fmt.Println("**********日志文件创建失败**********")
		fmt.Println(src, err)
		return nil
	}
```
这里，打开文件的方式是 只写的方式追加 os.O_APPEND|os.O_WRONLY，而且，如果打开失败，就会返回一个nil，**代码（报错）诚不欺我啊**：

`runtime error: invalid memory address or nil pointer dereference`

果真是代码中存在nil pointer

解决方式：
一方面：在初始化router的时候，判空一下，如果自定义失败，就使用默认的
```go
	var router *gin.Engine

	//使用自定义日志框架
	myLogger := middleware.LoggerToFile()
	if myLogger != nil {
		router = gin.New()
		router.Use(myLogger, gin.Recovery())
	} else {
		router = gin.Default()
	}
```
另一方面：文件打开方式改为为(清空|读写|创建，追加)如果不存在就创建，如果已存在就清空。因为他这个日志中间件会根据日期生成一个新的软链文件，所以，清空当前文件是没关系的。
```go
	//src, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, os.ModeAppend)
	src, err := os.OpenFile(fileName, os.O_TRUNC|os.O_RDWR|os.O_CREATE, os.ModeAppend)
```

<pre>
    <details>
    	<summary>👈点击展开 | 坑人的log中间件完整源码，我把它折叠起来了</summary>
package middleware
import (
	"fmt"
	"github.com/gin-gonic/gin"
	rotatelogs "github.com/lestrrat-go/file-rotatelogs"
	"github.com/rifflock/lfshook"
	"github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	"os"
	"path"
	"time"
)
// 日志记录到文件
func LoggerToFile() gin.HandlerFunc {
	logFilePath := viper.GetString("app.logFilePath")
	logFileName := viper.GetString("app.logFileName")
	// 日志文件
	fileName := path.Join(logFilePath, logFileName)
	// 写入文件
	src, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, os.ModeAppend)
	if err != nil {
		// 如果创建失败，尝试手动创建一下
		fmt.Println("**********日志文件创建失败**********")
		fmt.Println(src, err)
		return nil
	}
	// 实例化
	logger := logrus.New()
	// 设置输出
	logger.Out = src
	// 设置日志级别
	logger.SetLevel(logrus.DebugLevel)
	// 设置 rotatelogs
	logWriter, err := rotatelogs.New(
		// 分割后的文件名称
		fileName+".%Y%m%d.log",
		// 生成软链，指向最新日志文件
		rotatelogs.WithLinkName(fileName),
		// 设置最大保存时间(7天)
		rotatelogs.WithMaxAge(7*24*time.Hour),
		// 设置日志切割时间间隔(1天)
		rotatelogs.WithRotationTime(24*time.Hour),
	)
	writeMap := lfshook.WriterMap{
		logrus.InfoLevel:  logWriter,
		logrus.FatalLevel: logWriter,
		logrus.DebugLevel: logWriter,
		logrus.WarnLevel:  logWriter,
		logrus.ErrorLevel: logWriter,
		logrus.PanicLevel: logWriter,
	}
	// 设置日志格式-Json格式
	// 单独格式化日期
	lfHook := lfshook.NewHook(writeMap, &logrus.JSONFormatter{
		TimestampFormat: "2006-01-02 15:04:05",
	})
	// 新增 Hook
	logger.AddHook(lfHook)
	return func(c *gin.Context) {
		// 开始时间
		startTime := time.Now()
		// 处理请求
		c.Next()
		// 结束时间
		endTime := time.Now()
		// 执行时间
		executionTime := endTime.Sub(startTime)
		// 请求方式
		reqMethod := c.Request.Method
		// 请求路由
		reqUri := c.Request.RequestURI
		// 状态码
		statusCode := c.Writer.Status()
		// 请求IP
		clientIP := c.ClientIP()
		// 日志输出格式
		// 输出到文件
		logger.WithFields(logrus.Fields{
			"req_method":     reqMethod,
			"req_uri":        reqUri,
			"status_code":    statusCode,
			"execution_time": executionTime,
			"client_ip":      clientIP,
		}).Info()
	}
}
// 日志记录到 MongoDB
func LoggerToMongo() gin.HandlerFunc {
	return func(c *gin.Context) {
	}
}
// 日志记录到 ES
func LoggerToES() gin.HandlerFunc {
	return func(c *gin.Context) {
	}
}
// 日志记录到 MQ
func LoggerToMQ() gin.HandlerFunc {
	return func(c *gin.Context) {
	}
}
    </details>
</pre>


<pre>
    <details>
    	<summary>👈点击展开 | 修改后的log中间件完整源码，太长，折叠起来了</summary>
package middleware
import (
	"fmt"
	"github.com/gin-gonic/gin"
	rotatelogs "github.com/lestrrat-go/file-rotatelogs"
	"github.com/rifflock/lfshook"
	"github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	"os"
	"path"
	"time"
)
// 日志记录到文件
func LoggerToFile() gin.HandlerFunc {
	logFilePath := viper.GetString("app.logFilePath")
	logFileName := viper.GetString("app.logFileName")
	// 日志文件
	fileName := path.Join(logFilePath, logFileName)
	// 写入文件
	//src, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, os.ModeAppend)
	src, err := os.OpenFile(fileName, os.O_TRUNC|os.O_RDWR|os.O_CREATE, os.ModeAppend)
	if err != nil {
		// 如果创建失败，尝试手动创建一下
		fmt.Println("**********日志文件创建失败**********")
		fmt.Println(src, err)
		return nil
	}
	fmt.Println("**********日志文件创建成功**********")
	// 实例化
	logger := logrus.New()
	// 设置输出
	logger.Out = src
	// 设置日志级别
	logger.SetLevel(logrus.DebugLevel)
	// 设置 rotatelogs
	logWriter, err := rotatelogs.New(
		// 分割后的文件名称
		fileName+".%Y%m%d.log",
		// 生成软链，指向最新日志文件
		rotatelogs.WithLinkName(fileName),
		// 设置最大保存时间(7天)
		rotatelogs.WithMaxAge(7*24*time.Hour),
		// 设置日志切割时间间隔(1天)
		rotatelogs.WithRotationTime(24*time.Hour),
	)
	writeMap := lfshook.WriterMap{
		logrus.InfoLevel:  logWriter,
		logrus.FatalLevel: logWriter,
		logrus.DebugLevel: logWriter,
		logrus.WarnLevel:  logWriter,
		logrus.ErrorLevel: logWriter,
		logrus.PanicLevel: logWriter,
	}
	// 设置日志格式-文本格式
	// 单独格式化日期
	//logger.SetFormatter(&logrus.TextFormatter{
	//	TimestampFormat:"2006-01-02 15:04:05",
	//})
	// 设置日志格式-Json格式
	// 单独格式化日期
	lfHook := lfshook.NewHook(writeMap, &logrus.JSONFormatter{
		TimestampFormat: "2006-01-02 15:04:05",
	})
	// 新增 Hook
	logger.AddHook(lfHook)
	return func(c *gin.Context) {
		// 开始时间
		startTime := time.Now()
		// 处理请求
		c.Next()
		// 结束时间
		endTime := time.Now()
		// 执行时间
		executionTime := endTime.Sub(startTime)
		// 请求方式
		reqMethod := c.Request.Method
		// 请求路由
		reqUri := c.Request.RequestURI
		// 状态码
		statusCode := c.Writer.Status()
		// 请求IP
		clientIP := c.ClientIP()
		// 日志输出格式
		// 输出到文件
		logger.WithFields(logrus.Fields{
			"req_method":     reqMethod,
			"req_uri":        reqUri,
			"status_code":    statusCode,
			"execution_time": executionTime,
			"client_ip":      clientIP,
		}).Info()
		// 输出到控制台
		fmt.Println("------------------------ Request ------------------------")
		fmt.Printf(
			"req_method: %s | req_uri: %s | status_code: %d | execution_time: %s | client_ip: %s\n",
			reqMethod, reqUri, statusCode, executionTime, clientIP)
	}
}
// 日志记录到 MongoDB
func LoggerToMongo() gin.HandlerFunc {
	return func(c *gin.Context) {}
}
// 日志记录到 ES
func LoggerToES() gin.HandlerFunc {
	return func(c *gin.Context) {}
}

// 日志记录到 MQ
func LoggerToMQ() gin.HandlerFunc {
	return func(c *gin.Context) {}
}
    </details>
</pre>
