### ISSUE TITLE
能不能加一个登录授权的功能啊

### ISSUE THREAD

**Issue by hawind** [link1st/gowebsocket#14]
比如我集成在自己的系统里，前端要直接连接到websocket服务上，后端还要用http发信息到websocket上，那这个安全的问题应该怎么做呢

**Comment by link1st** [comment]
由于每个系统的权限认证是不同的，所以这边没有做权限认证

HTTP 接口和 webSocket 连接以后都是预留了可以进行权限认证的地方，在做系统集成的时候需要对项目进行改造，在这些位置添加相应的权限认证即可

添加权限认证的地方:

[给用户发消息Http接口控制器](https://github.com/link1st/gowebsocket/blob/master/controllers/user/user_controller.go#L67)

[webSocket建立连接以后登录](https://github.com/link1st/gowebsocket/blob/master/servers/websocket/acc_controller.go#L49)
