### ISSUE TITLE
关于掉线问题

### ISSUE THREAD

**Issue by 812169562** [link1st/gowebsocket#15]
测试的时候，短时间登录上200时候(测试机器8G内存) 突然就会有好几十账号突然掉线。而且用NGINX 配置wss,跑不上40个链接，到了40左右其他账户马上全部掉线。请问这个可能是什么问题呢

**Comment by link1st** [comment]
是不是连接登录的时候没有发送心跳包？

可能掉线的原因:
1、在使用 nginx 的时候，nginx 对长时间不活跃的长连接会主动断开`keepalive_timeout`
2、程序会定时清除不活跃连接，[防止内存溢出和Goroutine不回收](https://github.com/link1st/gowebsocket#318-%E9%98%B2%E6%AD%A2%E5%86%85%E5%AD%98%E6%BA%A2%E5%87%BA%E5%92%8Cgoroutine%E4%B8%8D%E5%9B%9E%E6%94%B6) 默认是6分钟没有发心跳的连接会被清除

**Comment by 812169562** [comment]
不是这个原因，我测试连接登录（总共耗时时间没有6分钟，大约开始连接几秒之内就有用户掉线），redis里面的数据都是插入成功的，所以没有到服务器清理不活跃的连接啊。这是我测试数据里
面有2000连接数，因为自己改了授权所以只能用此测试，已经测试过连接掉线和授权无关
 用户列表数据不断看见掉线。

**Comment by link1st** [comment]
试试用户数少一些是否也会掉线呢

查看程序日志 ，是否有关于掉线的原因有日志输出

查看是客户端主动断开、nginx断开、还是gowebSockt断开连接的，缩小问题的范围

**Comment by 812169562** [comment]
我看了一下都是：读取客户端数据 错误 websocket: close 1006 (abnormal closure): unexpected EOF，这个应该是nginx  Keepalive发空数据，服务端不能解析导致掉线的吗？

**Comment by link1st** [comment]
可以把nginx 关于timeout都设置大一些，看看是否能解决你的问题
```
http {
    ...

    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    proxy_read_timeout 300;
    send_timeout 300;

    ...
}
```

原因可能是nginx/客户端的问题

**Comment by 812169562** [comment]
也不得行，我再找找吧，基本上确定再nginx配置问题

**Comment by link1st** [comment]
建议把客户端也排查一下，是否建立连接数过多的时候就会出现断开连接的现象呢？

客户端有最大连接数的限制，或者是换别的客户端调试呢
nginx一般都是设置连接超时，如果不是超时一般都不是nginx问题
