### ISSUE TITLE
支持分组发送吗

### ISSUE THREAD

**Issue by golang730** [link1st/gowebsocket#16]

**Comment by link1st** [comment]
目前架构设计是把所有人拉到一个群，只实现了群聊的功能

分组的功能需要自行根据需要进行改造一下

**Comment by golang730** [comment]
怕没有，大佬写的好，大佬能不能实现这个功能呢，用的人会很多的，另外大佬能建一个群最好了，交流起来方便

**Comment by hawind** [comment]
这个库设计的很棒，也在使用，希望作者加强啊

**Comment by link1st** [comment]
@Dante666999 @hawind 

你们可以添加我的微信，我这边建立一个群，看看了解你们的需求

[加我好友](https://github.com/link1st/gowebsocket#%E6%84%8F%E8%A7%81%E5%8F%8D%E9%A6%88)

**Comment by link1st** [comment]
done

设置全部聊天室

https://github.com/link1st/gowebsocket/blob/cacb31fcea5c50af3319964d0782db8ffe222e97/servers/websocket/init_acc.go#L26

[http://im.91vh.com/home/index?appId=102](http://im.91vh.com/home/index?appId=102) 进入某个聊天室

[接口文档](https://github.com/link1st/gowebsocket#4411-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)

[更新代码 committed](https://github.com/link1st/gowebsocket/commit/cacb31fcea5c50af3319964d0782db8ffe222e97)

**Comment by solitudealma** [comment]
今天刚刚实现了一下分组房间的通信，我也看过其他项目的分组实现，实际上就是在clientmanager结构体加上一个map类型的rooms（因为我写的是游戏），用于存储不同房间用户的链接，然后key是房间名，value是client类型的切片。这样就能在controller处理不同房间的广播要求了。rooms是否同步到redis就看业务需要了
