### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by beikege** [link1st/gowebsocket#17]
https://github.com/link1st/gowebsocket/blob/cf343308c549dbca12b53c2a6d929cad929feb95/servers/websocket/client_manager.go#L181-L197

为什么使用 全局变量 clientManager 而不是 方法接收者变量 manager ,是手误还是有啥讲究?

https://github.com/link1st/gowebsocket/blob/cf343308c549dbca12b53c2a6d929cad929feb95/servers/websocket/client_manager.go#L134-L138

这里的 len 需要加锁吗?

**Comment by link1st** [comment]
已经更正，这个位置应该用 manager 更规范一些
https://github.com/link1st/gowebsocket/blob/751107a7030b0bfc4788b3e195b6b2d0fbdd5462/servers/websocket/client_manager.go#L181-L197

`manager.Users` 是 map 类型，map 添加锁的目的是: 在并发的情况下会出现**并发读写**的问题

在map的实现中，获取 len 没有并发读写的问题，所以这里可以不用添加锁

**Comment by beikege** [comment]
谢谢,解决了我的一些疑问.
