### ISSUE TITLE
适配手机端，可能的选项之一

### ISSUE THREAD

**Issue by zkbqhuang** [link1st/gowebsocket#18]
Vuejs+Vuetify+nuxtjs

https://cn.vuejs.org/
https://vuetifyjs.com/zh-Hans/
https://www.nuxtjs.cn/

**Comment by link1st** [comment]
我的前端技术比较薄弱，一直想着优化前端的界面适配手机端、聊天添加表情等，可惜有心无力

谢谢给技术方向

有没有兴趣帮忙一起优化手机适配、修改一些界面风格？

**Comment by zkbqhuang** [comment]
我水平也是很有限，也是刚刚关注到前端内容，怕是目前还帮不上什么忙，我关注到go的性能，和vue前端的在国人用的比较多一点，也一直想综合此两者进行使用，所以才多加推荐。

同时也希望有vue高手看到这个issue 来此与你达成合作，也会去其他类似需求的前端项目多推荐gowebsocket。毕竟多交流对自己的学习总是有好处的。

另外你谈到的聊天表情方面，或许可能在这个里面找到一些答案。
https://github.com/saucxs/happy-chat-web
但它并没用Vuetify（一个Material Design风格的vue UI框架，主要是能更美观一点）
它的后端用的nodejs。你看看后说不定能直接用go替代上。

**Comment by link1st** [comment]
谢谢热心的推荐，这个对我很有帮助

我也希望可以找到一个vue的高手，把这个项目的前端好好优化一下。

**Comment by gogogo1688** [comment]
有一个现成的前端扩展
https://www.layui.com/layim/
