### ISSUE TITLE
一个用户重复登录的问题。

### ISSUE THREAD

**Issue by billytoe** [link1st/gowebsocket#19]
当用 userId 为同一个id 时，再次登录时，而先前登录的 则收不到信息。

不是知道 底层是否如下描述？

限制已经登录的 不能再次登录，必须执行在异地或本地另开网页，输入密码执行退出登录前面的， 然后再次登陆,先前登录的则收到自己被迫下线。

**Comment by link1st** [comment]
用户的唯一标识是 userId ,这个用来限制用户的单点登录

单点登录限制: login 的接口中查看是否已经有存在的连接
不同平台登录限制: 如果一个用户可以在不同的 app 登录，同时接收消息可以用 appId 做区分 如: http://im.91vh.com/home/index?appId=102


发送消息都是更具appId和userId，去发送消息，当一个用户重复登录，通过 appId+userId 为key 去找用户的连接句柄只可能是一个。

[prc接口文档](https://github.com/link1st/gowebsocket#442-RPC%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3)

**Comment by billytoe** [comment]
感谢回答。 但我还是有点不明白。

1 appId=102 这个 我理解聊天房间的ID，同一个房间 用不同的app 或者是平台 比如手机安卓登录这个102房间，或者 是web页登录这个房间，或者是PC 端exe程序登录 这个102房间，是进入同一个房间ID。看您的意思 这 聊天房间的ID 和 app ID ，是一个东西？我的理解是不是分开两个ID ？

2 如果这个程序 目前支持多房间，不支持多用户从不同的平台登录同一房间的话，（我实际测试是 同一个userid 不能同时登录房间ID为102的房间，现象是  两次登录都是返回登录成功，但接下来 有一个客户端就收不到消息），是不是 只有 一种方法解决 就是 登录 提示 这个用户已经登录 无法继续登录？

**Comment by link1st** [comment]
最初的设计的系统没有 roomId 的概念，只有一个 appId，我用的是 appId 用来区分是不同的 **登录平台**，相同的 **登录平台** 才可以一起聊天，设计的时候是可以接入更多的应用 appId ,后来因为多个房间的需求，当时就直接改造成了用 appId 当 roomId 使用

问题一:
如果你们没有不同登录平台的的概念，可以把 appId 看错是 roomId，这样就能实现 只能一个平台登录，同时给不同群发消息

一个多个平台(appId),每个平台有不同的房间（roomId），在接口中添加一个roomId 字段就可以实现

问题二:
参考问题一，考虑好 appId 和 roomId 的关系
如果是多平台多房间，还需要添加 roomId 字段

**Comment by billytoe** [comment]
期待 多平台多房间，完美 支持 roomId ，我要加东西 可能会 把程序 搞乱 哈哈。

**Comment by link1st** [comment]
好的，后续计划会将 roomId 和 appId 分离开
