### ISSUE TITLE
怎样把用户的下线，上线，发送的文本等消息持久化存储 以便后续查询和管理？

### ISSUE THREAD

**Issue by billytoe** [link1st/gowebsocket#20]
我想使用mysql 持久化 是否可行 ？只 持久化Redis 可以吗？

**Comment by link1st** [comment]
用 mysql 持久化是可以的
在用登录、下线事件、发送文本消息的时候都在 mysql 中记录一下

**Comment by billytoe** [comment]
嗯嗯 非常感谢，

那是 在 server\websocket\client_manager.go 中的 
1 [用户断开连接 EventUnregister(client *Client)],

2 [用户登录  EventLogin(login *login)],

3 [发送数据 sendAppIdAll(message []byte, appId uint32, ignoreClient *Client)]

这三个事件函数里  写 插入数据库 的 代吗？

**Comment by link1st** [comment]
是的，这些都是用户动作的事件 
在这里记录一下存入数据库即可

**Comment by billytoe** [comment]
谢谢哈
