### ISSUE TITLE
服务重新部署时，socket会重连，那redis中存储的数据是不是需要清除？

### ISSUE THREAD

**Issue by shengbiaoguo** [link1st/gowebsocket#23]

**Comment by link1st** [comment]
处理过程:
1、redis 中的存的用户连接信息都是设置过期时间的(过期时间十分钟)，到期会自动清除
2、redis 存的用户信息有用户上一次心跳的时间，长时间未发心跳包可以判定用户已经失去了连接
3、服务器重启或者是用户断线重连，都会覆盖 Redis 中的用户连接信息

以上处理的时候基本可以满足大多数业务需求，所以本项目未用优雅重启的方式
