### ISSUE TITLE
打开页面后，进同一个聊天室，无法会话啊。

### ISSUE THREAD

**Issue by xinjiayu** [link1st/gowebsocket#26]
分别用不同的机器打开同一个聊天室的时候，各聊各的，不能一起聊天。

**Comment by link1st** [comment]
[项目使用说明](https://github.com/link1st/gowebsocket#12-%E9%A1%B9%E7%9B%AE%E4%BD%93%E9%AA%8C)
[项目启动说明](https://github.com/link1st/gowebsocket#43-%E9%A1%B9%E7%9B%AE%E5%90%AF%E5%8A%A8)
