### ISSUE TITLE
请问为什么使用 HTTP 方式发送消息？

### ISSUE THREAD

**Issue by rakuyoMo** [link1st/gowebsocket#27]
请问为什么不直接通过 WebSocket 向服务器发送消息，而是由客户端调用 HTTP 接口将消息数据传送至服务器后，服务器再发送 WebSocket 到目标客户端？这样设计有什么用意吗？

**Comment by link1st** [comment]
这个是项目的设计，通过将发消息 api 和长连接解耦，减少系统的依赖

**Comment by rakuyoMo** [comment]
> 这个是项目的设计，通过将发消息 api 和长连接解耦，减少系统的依赖

谢谢您的回答，但是有一点不太明白的是，服务器接收到发送消息请求后，不也是通过 WebSocket 转发该条消息到接收者吗？这样算是解耦吗？

**Comment by link1st** [comment]
上行消息和下行消息是不同的通道，上行的http、下行是tcp长连接
长连接服务万一宕机了，但是发消息还是正常(长连接服务器和IM聊天服务器可以是两组服务)

[项目架构设计](https://github.com/link1st/gowebsocket#41-%E9%A1%B9%E7%9B%AE%E8%AF%B4%E6%98%8E)

可以查看这里架构设计图，IM和长连接是解耦的，本项目只是为了演示方便 就放在一起的，其实这个可以是可以单独部
