### ISSUE TITLE
nginx会不会成为性能瓶颈？

### ISSUE THREAD

**Issue by peachestao** [link1st/gowebsocket#28]
你好，nginx做websocket代理转发要分别跟客户端和websocket服务维持长连接，对于websocket服务来说nginx也是客户端，一个客户端一个ip的话只能创建65535个长连接，那这是不是成了性能瓶颈了？

**Comment by link1st** [comment]
是的，如果使用nginx 由于固定客户端端口的限制，有可能会成为系统的瓶颈，单台 nginx 在不做虚拟IP的情况下，只能有65535个长连接

如果业务量比较大的时候，nginx 支持部署多台，nginx 只做代理，所以对机器性能要求很低

使用 nginx 的好处还是很多 [为什么使用nginx](https://github.com/link1st/gowebsocket#51-%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E9%85%8D%E7%BD%AEnginx)
减少入侵可能、负载均衡、不暴露内网IP、支持配置域名访问、ssl 证书等

权衡利弊以后，这里使用了nginx 做代理

**Comment by peachestao** [comment]
谢谢解答，业务量大的话nginx前面还得加一层负载均衡器，如LVS、FS。
另外再请教一下用nginx代理websocket,一个连接过来nignx是不是同时建立了客户端和nignx、nginx和提供websocket服务的机器的两个长连接？

**Comment by link1st** [comment]
> 另外再请教一下用nginx代理websocket,一个连接过来nignx是不是同时建立了客户端和nignx、nginx和提供websocket服务的机器的两个长连接？

是的，会有两个长连接

**Comment by taofei-pro** [comment]
麻烦问下，如何实现单台机器突破nginx65535端口的限制

**Comment by iluozhiqiang** [comment]
> 你好，nginx做websocket代理转发要分别跟客户端和websocket服务维持长连接，对于websocket服务来说nginx也是客户端，一个客户端一个ip的话只能创建65535个长连接，那这是不是成了性能瓶颈了？

这个理解是错的，连接数取决于四元组，就是出口IP:PORT及入口IP:PORT，服务器的入口IP及端口是固定的，但是客户端的IP和PORT是不固定的，所以理论上服务器可以达到连接数65535^2≈42亿。

但是理论和实际是有很大差距的，一般牛逼的设计可以让单机实现1000万，差一点的也可以达到100万级别。拿go做比方，一个go协程占用2~8kkb，加上一个连接的内存占用差不多算10kb。那么一百万需要差不多10g内存就够了。

65535的限制是linux限制了单进程允许控制的文件的最大数量，并非因为服务器只能运行这么多连接。所以可以了解下如何修改linux最大连接数的限制

**Comment by dongwflj** [comment]
> 客户

这个瓶颈指的是nginx作为客户端与websocket server创建连接，这时候nginx针对这台服务器最多65535条连接。
