### ISSUE TITLE
问下如何实现user to user 的点对点聊天？

### ISSUE THREAD

**Issue by jagaimotomato** [link1st/gowebsocket#29]
还有好友系统, 能不能给个思路

**Comment by link1st** [comment]
这里实现的是广播，是对所有人发送消息

只需要修改一下将广播，修改为对某个人发送就可以了
获取用户的连接 client , 然后调用 `SendMsg(message)` 方法就可以了

https://github.com/link1st/gowebsocket/blob/8c849c9f171de2e4892c29e07f5d302893b070d7/servers/websocket/client_manager.go#L120

需要注意的是，本系统没有做消息缓存，好友系统需要添加:
1、消息持久化
2、好友登录，推送历史未读消息

**Comment by jagaimotomato** [comment]
谢谢回答
