### ISSUE TITLE
如何和java通讯？

### ISSUE THREAD

**Issue by 0000005** [link1st/gowebsocket#31]
我们的业务后端是java，需求比较简单，就是把消息（相当于私信公告）推到前端去。
类似这个：
![image](https://user-images.githubusercontent.com/9690089/110189798-64036580-7e5b-11eb-8d45-2a1985e08008.png)

简单的业务流如下：
![image](https://user-images.githubusercontent.com/9690089/110189739-1850bc00-7e5b-11eb-8b6d-c8256b983b97.png)

我的问题是：java怎么调用gowebsocket发消息，有现成的方法吗？还是说java要模拟websocket和gowebsocket通讯才可以？

**Comment by 0000005** [comment]
看到了，有http接口

**Comment by ZAKLLL** [comment]
直接用java的webSocket不能满足需求吗
