### ISSUE TITLE
关于监听消息的疑问

### ISSUE THREAD

**Issue by 0000005** [link1st/gowebsocket#32]
我们在浏览器前端要监听2类消息，
- 私信
- 群消息（具体来说是给某一类用户广播消息）

建立1个websocket连接能不能做同时监听这两类消息？

**Comment by 0000005** [comment]
盼答复，谢谢作者

**Comment by link1st** [comment]
这种完全是可以的，可以在这里定义不同的 type 用于区分群聊和私信消息类型，如果这个结构体也可以自行扩展需要的字段

https://github.com/link1st/gowebsocket/blob/6854c2d895196590265d6746b70dc64f36f63d55/models/msg_model.go#L21

比如:
消息类型 text/img/私信/单聊

**Comment by mengdodo** [comment]
你这个需求，我觉得不应合在一起。单个用户数据交互，大厅广播，房间对战这些应该启单独的服务
