### ISSUE TITLE
你好，请问可以用您的项目来作为论文吗？

### ISSUE THREAD

**Issue by brejce** [link1st/gowebsocket#33]
我正在写一片论文，使用golang服务的+uni-app客户端，需要一些文档，看见您的项目，故想拿来参考一下，会拜读您的项目，理解后，进行重写，您的项目功能太多了，所以只会使用您的一部分功能。不会原封不动抄，望回复。

**Comment by link1st** [comment]
可以的，这个也是一个开源项目，可以将项目用来引用
