### ISSUE TITLE
关于心跳包的问题

### ISSUE THREAD

**Issue by mengdodo** [link1st/gowebsocket#35]
我看gorilla/websocket包使用的是`SetReadDeadline`、`SetPongHandler`实现的ping-pong，你这个项目是通过定时轮询整个clientIds+自定义heatbeat请求刷新心跳时间。
我想知道`SetReadDeadline`、`SetPongHandler`是不是更好的解决办法

**Comment by link1st** [comment]
`SetReadDeadline` `SetPongHandler` 是利用 tcp 协议的 ping-pong 实现的
本项目使用的是应用层控制心跳

tcp ping-pong 比较节约带宽、业务可以设置、处理的地方比较少

应用层控制心跳，业务可控程度比较高，请求和响应都可以有记录，方便排查问题
本项目记录了用户每次心跳的数据，连续三次心跳没有收到则判定用户掉线，进行下线处理


本项目使用应用层的心跳，也是出于上述考虑

**Comment by mengdodo** [comment]
@link1st 确实是，你设计的这个自定义程度更高，谢谢你
