### ISSUE TITLE
如何解决因为nginx端口限制导致的65535连接上限的问题

### ISSUE THREAD

**Issue by taofei-pro** [link1st/gowebsocket#36]
nginx的端口限制，导致了同时间最多只有65535的长连接，无法实现百万单台的需求

**Comment by taofei-pro** [comment]
![image](https://user-images.githubusercontent.com/28079815/118088776-27735d80-b3fa-11eb-9fb0-015761e28a74.png)
这个是否可以解决

**Comment by link1st** [comment]
可以解决的方法:
1、NGINX 和 gowebsocket server 放在同一台机器上，这样就不消耗出网端口了
2、不适用NGINX，直接使用 gowebsocket 对外提供服务
3、多台NGINX转发到一台  gowebsocket server 上

问题的原因:
> 由于linux端口的范围是 0~65535(2^16-1)这个和操作系统无关，不管linux是32位的还是64位的
> 这个数字是由于tcp协议决定的，tcp协议头部表示端口只有16位，所以最大值只有65535(如果每台机器多几个虚拟ip就能突破这个限制)
> 1024以下是系统保留端口，所以能使用的1024到65535

**Comment by taofei-pro** [comment]
采用虚拟IP的方式，可以解决端口受限的问题，目前11万长连接保持良好
