### ISSUE TITLE
grpc_server中QueryUsersOnline的疑问

### ISSUE THREAD

**Issue by zhouyb-cn** [link1st/gowebsocket#38]
感谢作者的开源项目，看了下源码，有两处疑问希望作者帮忙解答下，不确定是不是我有遗漏
### grpc_server中QueryUsersOnline
我理解的如果是分布式部署，所有机器共用一个redis的，用户在线信息是可以直接查redis拿到的，这里设计一个grpc的接口作用是啥呢，我想到一种，就是不能直接访问redis的服务，通过rpc调用去获得用户在线信息
### 源码中设计了通过心跳来维持用户在线信息，可是没有找到使用的地方
在这里 https://github.com/link1st/gowebsocket/blob/master/servers/websocket/user_srv.go#L103
只是把用户在线信息从redis中取出来，并没有检查其中的用户是否在线，其中有个心跳时间，还有个是否退出的标识，我的理解既然用心跳来维持用户在线状态了，是不是得检查下，这里是不是真的遗漏了，还是有其他考虑呢

**Comment by link1st** [comment]
1、我这边设计的微服务之间的调用，一个长连接服务和一个聊天服务，用户在线状态是 长链接信息维护，外部服务拿不到在线状态，需要推送、查询用户在线状态只能通过 RPC 的方式。
2、刚检查了一下代码，是属于我的遗漏
>  检查一下用户信息是否失效，在发送比较合适一点。
> 之前的考虑是: 
> 1、其它系统调用长连接系统，会先获取用户是否在线
> 2、redis 设置了过期，超时key 获取不到
https://github.com/link1st/gowebsocket/commit/ac89da2cf0f73fb9e808892de61ecdbeedc17486
```
	if !info.IsOnline() {
		fmt.Println("用户不在线", key)
		return false, nil
	}
```

**Comment by zhouyb-cn** [comment]
回复太快了，第二点正准备给你提PR呢，写好了准备提呢，回来一看已经修复了
感谢解答🙏
