### ISSUE TITLE
看不到图片，不知道是不是只是我的问题？

### ISSUE THREAD

**Issue by kaiktang** [link1st/gowebsocket#39]

**Comment by link1st** [comment]
我刚重新浏览了一下，是可以看到的图片的
如果有看不到的图片，可以帮忙指出在哪个位置吗？

**Comment by 0HappyWater0** [comment]
> 我刚重新浏览了一下，是可以看到的图片的 如果有看不到的图片，可以帮忙指出在哪个位置吗？

README中的图片貌似挂掉了，比如 网站架构图，HTTP协议和WebSocket比较，浏览器开始支持webSocket的版本。直接访问链接的话就是403。

这个项目写得很好，辛苦啦！

**Comment by link1st** [comment]
嗯嗯，之前一直使用的是免费的图床，导致一些图片未 403 无法访问
现在全部更新为 自己的阿里云对象存储了，现在可以正常查看图片了
