### ISSUE TITLE
ClearTimeoutConnections定时清理超时连接 问题

### ISSUE THREAD

**Issue by wangjiangit** [link1st/gowebsocket#44]
作者你好，在这个函数中是不是要增加 如果心跳超时，就要删除对于的 map  如 delete (client,*Client)防止key太多占内存, 同时设置对应的*UserOnline 为nil ,已清空变量及其redis 中UserOnline 的相应的键名

**Comment by link1st** [comment]
这里只清除了 map 中的用户连接，Redis key 设置了过期时间和上一次心跳的时间，Redis 中会自动清除，不需要处理 Redis 中的数据

-----------   补充回答
在 ClearTimeoutConnections  函数中 `client.Socket.Close()` 关闭 scoket 会触发 协程`write() defer`，在 defer 中会删除用户登录的 map 

[相关阅读](https://github.com/link1st/gowebsocket#318-%E9%98%B2%E6%AD%A2%E5%86%85%E5%AD%98%E6%BA%A2%E5%87%BA%E5%92%8Cgoroutine%E4%B8%8D%E5%9B%9E%E6%94%B6)
