### ISSUE TITLE
protobuf 生成协议报错

### ISSUE THREAD

**Issue by eetuuuu** [link1st/gowebsocket#45]
protoc --go_out=./ *.proto                            
protoc-gen-go: unable to determine Go import path for "im_protobuf.proto"

Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.

使用这个可以生成，与之前的比较又不一样。请问是用的那个版本，如何生成im_protobuf.pb.go 文件？
我用的方式是brew install protobuf
go get -u google.golang.org/protobuf/cmd/protoc-gen-go
go install google.golang.org/protobuf/cmd/protoc-gen-go
go get -u [google.golang.org/grpc/cmd/protoc-gen-go-grpc](http://google.golang.org/grpc/cmd/protoc-gen-go-grpc)
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

这个命令可以执行，但是与原来的不一样，代码未改动，我想生成一个。使用的是mac m1 
protoc -I=. --go_out=. --go-grpc_out=. im_protobuf.proto

**Comment by sobbk** [comment]
`protoc --go_out=. --go_opt=paths=source_relative  --go-grpc_out=. --go-grpc_opt=paths=source_relative helloworld/helloworld.proto`

**Comment by link1st** [comment]
由于 protoc 不同版本差异导致的，项目已经升级最新版本

https://github.com/link1st/gowebsocket/pull/47
