### ISSUE TITLE
maingo: run command at func open(） failed

### ISSUE THREAD

**Issue by gaoxiaoyu** [link1st/gowebsocket#46]
at main.go， command "open"  out is  "failed to call Output(): exec: "open": executable file not found in $PATH".
why run command "open httpurl" here？

func open() {

	time.Sleep(1000 * time.Millisecond)

	httpUrl := viper.GetString("app.httpUrl")
	httpUrl = "http://" + httpUrl + "/home/index"

	fmt.Println("访问页面体验:", httpUrl)

	cmd := exec.Command("open", httpUrl)
	cmd.Output()
}

**Comment by link1st** [comment]
This is a quick access experience address, which is generally used by novices who are not familiar with this project.
