### ISSUE TITLE
大佬你好，请教一个问题

### ISSUE THREAD

**Issue by callmePicacho** [link1st/gowebsocket#50]
为什么一个连接进入，首先会有 Register，再然后才是 Login，是因为没有登录功能而做的妥协吗？或者是基于其他什么考虑呢？望回复，另外这个项目给我帮助很大，请问有交流群可以分享一下吗？

**Comment by link1st** [comment]
Register 是指 **acc_routers.go** 中 webSocket 路由注册码?
> webSocket 路由的设计模式是: socket 是流式数据，长连接的方式收发消息 (有着 无固定请求协议、只有读消息和写消息两种处理方式，回复消息也不确定是回复的是哪一次请求 等问题)，使用 webSocket 路由注册是将流式方式修改为 类似于 HTTP 接口路由的方式处理，方便代码开发、业务逻辑处理。

服务启动时先 Register webSocket 路由
当用户连接以后 首先发送 `cmd: "login"` 请求，进行用户鉴权，鉴权以后后续操作都不需要鉴权

请问有交流群可以分享一下吗？
> 目前没有交流群，issues 提出问题都可以得到回复的。

**Comment by callmePicacho** [comment]
之前问题没有描述清楚，我再重新描述一遍，并做答复，有不正确的地方请大佬不吝指教！
代码逻辑：
1. 在 `wsPage()` 处理函数中，每当有 websocket 连接进入，New 出一个 client，这个 client 开启读写线程，并且向 `clientManager.Register`  channel 中写入，在 `ClientManager.start()` 方法中，会调用 `manager.EventRegister()` 建立连接
2. websocket 连接接入后，还需要发送 cmd 为 `login` 的消息，进行用户登录，处理后会向 `clientManager.Login` 这个 channel 写入，同样会在 `ClientManager.start()` 方法中，调用 `manager.EventLogin()` 执行登录

问题描述：
之前认为，先向 `clientManager.Register` 发送建立连接事件，后又向 `clientManager.Login` 是由于大佬的系统中没有 HTTP 登录功能，而选择在 websocket 中做登录，所以是否能把 Login 做的事都放到 Register 中

现在认为，即使是有 HTTP 登录功能，也需要 websocket 建立连接后进行登录，原因如下：
1. 根据 websocket 建立连接的过程，客户端向服务端首先发送 HTTP 请求，即前面的建立连接事件产生，此时 websocket 连接还未真正建立完成，还需要 websocket 服务端返回客户端 HTTP 响应
2. 拆分成两个事件，提高代码可读性和可扩展性

**Comment by link1st** [comment]
1、webSocket 协议是先建立 HTTP 协议，然后由服务端返回升级响应 `Upgrade: websocket`，升级到 webSocket ，只有客户端接受了升级请求，才算连接建立完成
[](https://github.com/link1st/gowebsocket#21-websocket-%E6%98%AF%E4%BB%80%E4%B9%88)
2、拆分 read、write 两个协程处理，提升代码可读性、扩展性，同时也方便客户端消息收发不相互影响。
