### ISSUE TITLE
分布式为啥不使用Redis的发布/订阅机制

### ISSUE THREAD

**Issue by taofei-pro** [link1st/gowebsocket#51]

**Comment by link1st** [comment]
分布式一般指分布式系统，支持水平扩展、并行处理、资源共享等
> “分布式系统是若干独立计算机的集合，这些计算机对于用户来说就像是单个相关系统”

Redis的发布/订阅机制，是一种消息通讯模式
> 是一种消息通信模式：发送者(pub) 发送消息，订阅者(sub) 接收消息

两者不是一种概念，本项目通过集中式消息共享，支持服务水平进行扩展，实现了分布式系统
在实现 IM 系统，使用 go webSocket 实现即时通讯系统，虽然业内也有通过 Redis 发布订阅机制实现即时通讯的，但是 Redis 也存在一些缺点，必须先执行订阅，再等待消息发布、也没有ACK机制 等问题，本项目可以解决这些问题，而且在性能上也支持单节点百万用户同时在线。

**Comment by taofei-pro** [comment]
服务器与服务器之间的通信，现在依赖的是rpc通信，会存在服务器之间相互调用rpc的情况，这个部分可以依靠redis的消息通讯模式或者消息队列，这样可以不起rpc服务，需要给其他服务器发消息，就给redis中发布，其他服务器再各自订阅redis中的消息，来实现相互之间的通信

**Comment by link1st** [comment]
服务端通讯主流方式还是 RPC，如 gRPC、Thrift、Dubbo、Spring Cloud等
> RPC（Remote Procedure Call Protocol）远程过程调用协议  

RPC 既然是协议就只是一套规范，有着 网络协议和网络IO模型对其透明、信息格式对其透明、应该有跨语言能力等优势，
远程调用和调用本地的方法一样方便。

Redis 发布/订阅的能力虽然也能实现远程通讯，但是在 路由选择、熔断、限流、过载保护、降级、编解码、数据序列化、压缩等方面没有现成的方案，使用Redis作为中间件具有单点故障和多一个层网络调用 (服务A => Redis server => 服务B)，在网络稳定性、网络耗时都会有所增加。

参考:
[如何设计一个 RPC 系统](https://cloud.tencent.com/developer/article/1004410)

**Comment by taofei-pro** [comment]
使用RPC的话，每台服务器都需要起RPC服务，然后服务器之间通过RPC相互调用（服务A<=>服务B、服务B<=>服务C、服务A<=>服务C、服务A<=>服务D、服务B<=>服务D、。。。），随着服务器的增多，相互调用关系成指数上升；使用Redis的发布/订阅作为中间件，就可以不需要启动RPC服务，每台服务器都订阅Redis，需要传递信息时，只需要向Redis中发布消息（服务A<=>Redis、服务B<=>Redis、服务C<=>Redis、服务D<=>Redis、。。。），相互调用关系是线性上升。

**Comment by link1st** [comment]
这里有一个误区，就是每个服务和 Redis 交互就结束了，其次是 RPC 调用都是为了完成一定的服务，Redis 的订阅发布不具有这些能力(给客户端推送消息、查询用户连接服务器节点)

如果使用 Redis ，调用流程如下，会有两次网络存储
> 服务 B 通过 Redis SUBSCRIBE "频道 B"
> 服务 A 找到用户连接的服务 B 订阅的"频道 B"
> 服务 A 给 Redis  PUBLISH "频道 B" 消息
> 服务 B 收到订阅消息，然后进行处理


比如本项目
> 需要做到用户消息推送，服务 A 找到用户连接的服务B，RPC 调用服务 B 就可以将消息推送下去，这里是涉及一次网络调用。
