### ISSUE TITLE
有更新的目录划分吗？

### ISSUE THREAD

**Issue by kureCC** [link1st/gowebsocket#59]
![image](https://github.com/link1st/gowebsocket/assets/50306828/f2830d71-c6e3-4fde-a7aa-caa75e924ffa)
acc_controller里的方法越来越多，怎么拆分出去。直接拆会循环引用包

**Comment by link1st** [comment]
这里应该按功能划分目录，模块、主题或功能来命名目录。如 登录、任务、各种活动等，确保新的目录结构清晰、易于理解和维护。

这里拆分，必须没有相互引用，如果有相互调用则表示这两个功能有交集，就应该放在一个目录中。

**Comment by kureCC** [comment]
未来我的acc_controller会有很多事件，我已经尝试按功能拆分了，但是因为map订阅的方法使用了client，所以会循环引用包，有好的方法吗？
咱们有qq或者微信群吗？想要交流一下

**Comment by kureCC** [comment]
可以给一个示例参考下吗？

**Comment by link1st** [comment]
这个一般和业务耦合，我只能提供我们线上的业务给你参考一下

- v1
- 业务有一个中间层 service ，用于处理通用的逻辑，尽量和业务解耦
- controller 调用 中间层 处理成为接口所需要的数据
> match、stat、text_live 三个目录

```
├── service  # 中间层逻辑处理
│   ├── match.go # 比赛基础数据
│   ├── stat.go # 比赛数据统计
│   ├── text_live.go # 图文直播
├── controller # 控制器
│   ├── match # 比赛基本数据
│   │   └── match.go # 比赛API
│   ├── stat # 赛事统计
│   │   └── stat.go # 统计API
│   ├── text_live # 图文直播
│   │   └── text_live.go # 图文直播 API

```

- v2 需要比赛和数据统计，则需要 match stat 目录相互调用，
- 则把match，和 stat 目录合并
> matchstat 目录

```
├── service  # 中间层逻辑处理
│   ├── match.go # 比赛基础数据
│   ├── stat.go # 比赛数据统计
│   ├── text_live.go # 图文直播
├── controller # 控制器
│   ├── matchstat # 比赛基本数据
│   │   └── match.go # 比赛API
│   │   └── match_stat.go # 比赛和数据统计 API
│   │   └── stat.go # 统计API
│   ├── text_live # 图文直播
│   │   └── text_live.go # 图文直播 API

```

**Comment by kureCC** [comment]
├── controller # 控制器
│   ├── match # 比赛基本数据
│   │   └── match.go # 比赛API
这里的match里面使用了client吗？不会出现循环引用包吗？

**Comment by kureCC** [comment]
https://github.com/buexplain/netsvr/blob/main/test/business/cmd/business.go
我参考了下这个项目的注册方式，解决了循环引用包的问题
