### ISSUE TITLE
websocket高可用如何实现向指定的客户端发送消息？

### ISSUE THREAD

**Issue by colinlabs** [link1st/gowebsocket#6]
老师，您好。看你这个项目是使用nginx做的负载均衡，我有一个疑问：
- 现有server A和server B
- 客户端向服务端建立连接: client A -> server A
- 如果使用API方式，调用websocket集群，向client A发送消息。因clientA是与server A建立的长连接，如何保障消息是通过server A发送到client A的，server B是没法发送消息到client A的？

**Comment by link1st** [comment]
你好:

水平部署的项目之前可以内部相互通讯，分布式项目从外面看像一个整体，消息发给这个整体就一定能发送给这个用户。

1. 如果这个请求发送 Server B 上( Client A 连在 Server A上)
2. Server B 会查询 Redis，找到Client A连接上的 Server A
3. Server B -> Server A (gRpc的方式)发送消息
4. Server A 再把消息发送给 ClientA


具体原理参考 7.2 架构 节[给用户发送消息时序图](https://github.com/link1st/gowebsocket#72-%E6%9E%B6%E6%9E%84)

**Comment by colinlabs** [comment]
谢谢，明白了，很清晰。 这里的gRPC的主要作用是服务端之间相互发消息，是吧？

**Comment by link1st** [comment]
是的，gRpc主要是微服务服务端之间相互通讯
