### ISSUE TITLE
有个疑问,为什么客户端不使用websocket send的方式发送消息

### ISSUE THREAD

**Issue by ekk0** [link1st/gowebsocket#62]
WebSocket 与客户端建立持久的双向通信连接，这样客户端可以直接通过 WebSocket 连接发送和接收实时的消息，而不需要每次都发起一个新的 HTTP 请求。这种实时性对于即时聊天应用非常重要，因为它允许消息的快速传递和实时更新。
使用 HTTP 发送消息需要建立一个新的请求-响应循环，每次发送消息都需要发起一个新的 HTTP 请求，这会引入较大的延迟，并且增加服务器的负载。使用 WebSocket 可以在客户端和服务器之间建立实时的双向通信，服务器可以直接将消息推送到客户端，而不需要等待客户端发起请求。

**Comment by link1st** [comment]
[7.1 说明 中有解释](https://github.com/link1st/gowebsocket#71-%E8%AF%B4%E6%98%8E)

采用 HTTP 发送消息，为了收发数据分离，进行数据解耦，提升发送数据的成功率。
