### ISSUE TITLE
基于收发数据分离，相比webSocket，整个项目似乎更适合用SSE EventSource实现

### ISSUE THREAD

**Issue by AOEIUVBPMFDTNL** [link1st/gowebsocket#63]
```
采用 HTTP 发送消息，为了收发数据分离，进行数据解耦，提升发送数据的成功率。
```
- 服务分离，让acc系统尽量的简单一点，不掺杂其它业务逻辑
- 发送消息是走http接口，不使用webSocket连接，采用收和发送数据分离的方式，可以加快收发数据的效率

基于这个项目的websocket只用于推送消息到客户端，而客户端发送消息则调用http接口，那么SSE似乎是一个更好的选择。

这个项目和 [gochat](https://github.com/LockGit/gochat) 不同，客户端使用http接口来发消息，而不是使用grpc proto来通信，项目中的grpc仅用于服务间的通讯，那么websocket相对于SSE支持二进制和客户端主动发消息的双向通讯优势也就没有了，剩下的相比SSE全是劣势。

[Gin server-sent-event 示例](https://github.com/gin-gonic/examples/blob/master/server-sent-event/main.go)

[Gin realtime-advanced 示例](https://github.com/gin-gonic/examples/tree/master/realtime-advanced)

[Gin realtime-chat 示例](https://github.com/gin-gonic/examples/tree/master/realtime-chat)

gin本身对SSE提供了支持，前端用起来更简单，创建一个EventSource对象就可以实现对数据流的监听，不需要前端去考虑断线重连，心跳等问题，同时还支持服务优雅降级，支持单独特定事件监听，也可指定事件ID等。

每个websocket服务的单一责任就是推消息到客户端，客户端则通过接口来发消息，那么选择更简单更轻量的SSE似乎更好。

**Comment by link1st** [comment]
Server-Sent Events (SSE) 和 WebSocket 是两种不同的通信协议，它们都用于在客户端和服务器之间实现实时通信，但它们在某些方面有一些重要的区别。以下是它们之间的比较：

1. 连接建立方式：
   - SSE：Server-Sent Events 是一种基于HTTP的单向通信协议。客户端通过简单的HTTP请求（通常是GET请求）来连接服务器，服务器然后可以随时发送数据给客户端。连接是由服务器始终保持打开的，直到客户端关闭连接为止。
   - WebSocket：WebSocket 是一种全双工通信协议，客户端和服务器之间可以双向发送数据。WebSocket 连接是通过在HTTP握手之后升级到WebSocket协议来建立的，这意味着连接一旦建立，它将一直保持打开状态，而不需要每次请求都重新建立连接。

2. 数据格式：
   - SSE：数据以文本格式传输，通常使用纯文本或JSON格式。服务器可以周期性地向客户端发送新数据。
   - WebSocket：WebSocket 支持双向数据传输，并且数据可以以二进制格式传输，因此更灵活。它可以用于流媒体、在线游戏等需要实时双向通信的应用。

3. 浏览器支持：
   - SSE：Server-Sent Events 在现代浏览器中得到了广泛支持，但在一些旧版本的浏览器中可能存在兼容性问题。
   - WebSocket：WebSocket 在现代浏览器中也得到了广泛支持，但与SSE不同，WebSocket可以通过库或框架在旧版本浏览器中进行模拟。

4. 用途：
   - SSE：Server-Sent Events 适用于一些简单的实时通知场景，如新闻更新、股票报价、天气通知等。
   - WebSocket：WebSocket 更适用于需要双向通信、低延迟和高度互动性的应用，如在线游戏、聊天应用、协作工具等。

5. 简易性：
   - SSE：Server-Sent Events 更容易使用，因为它是基于HTTP的，不需要复杂的握手过程。
   - WebSocket：WebSocket 需要进行握手协议，因此相对复杂一些。

6. 服务器支持：
   - SSE：SSE 可以在标准的HTTP服务器上实现，无需特殊的服务器支持。
   - WebSocket：WebSocket 需要特殊的服务器支持，通常需要使用WebSocket服务器或在现有服务器上添加WebSocket支持。

总的来说，选择使用 SSE 还是 WebSocket 取决于您的应用需求。如果只需要单向通知或简单的实时数据推送，SSE 是一个不错的选择。如果需要双向通信、更高的互动性和更复杂的应用，WebSocket 可能更适合。
