### ISSUE TITLE
重发

### ISSUE THREAD

**Issue by Nothing0v0** [link1st/gowebsocket#65]
想问下如果短时间内有大量消息发送，是否有些消息用户收不到，或者用户过多，某些用户收不到某条消息，是否有上述两种情况。如果有，那是怎么检测并重发的呢。如果没有，又是怎么保证的呢。

**Comment by link1st** [comment]
消息推送是一种在实时通信应用和服务中常见的需求，但在网络环境中，无法百分之百地保证消息的到达。可以采用一些策略和技术来保证消息可靠性，

消息确认机制：要求接收方发送确认消息，以确认消息的接收。如果发送方没有收到确认，可以进行重传。这是一种简单而有效的方法，可确保消息已经成功到达。
重试机制：在消息发送失败时，实施一定的重试策略，以尝试重新发送消息。这可以在一定程度上弥补瞬时的通信问题。
消息持久化：将消息持久化存储，以防止消息丢失。这可以通过将消息存储在数据库或日志文件中来实现。
消息队列和推送服务：使用消息队列系统和推送服务来管理消息传递。这些系统通常提供持久性、消息确认和重试机制，以提高消息的可靠性。
