### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by Agelessbaby** [link1st/gowebsocket#69]
为什么我在服务器上跑起来，在聊天室内发送消息没有反应，也没有给我生成用户名，可能是因为哪些问题呢？

**Comment by link1st** [comment]
可以在 log 目录查看运行日志结果，建议检查 config 配置是否正确。

**Comment by Agelessbaby** [comment]
你好，我发现是键入url的问题，如果按照项目的提示，使用http://的话会出现该问题，不键入协议直接访问端口，浏览器应该默认使用ws，这样就可以正常发送消息了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Link ***@***.***&gt;
发送时间: 2023年11月21日 19:58
收件人: link1st/gowebsocket ***@***.***&gt;
抄送: Agelessbaby ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [link1st/gowebsocket] 一个小问题 (Issue #69)





 
可以在 log 目录查看运行日志结果，建议检查 config 配置是否正确。
