### ISSUE TITLE
client manager 中两个小问题

### ISSUE THREAD

**Issue by lemonash** [link1st/gowebsocket#7]
client_manager.go中ClearTimeoutConnections
1.client manager遍历时没加锁；
2.client关闭的时候，client中的SendChan没关闭，clients的map中没有删除这个client。

不知道说的对不对。从你的项目吸收了不少东西，借此感谢！

**Comment by link1st** [comment]
如果这个项目能给你可以借鉴的东西，已经是对我写这个项目最大的肯定了。

#### 问题一：

在最初的版本的确有遍历 map 没有加锁的情况，压测的时候出现并发读写的问题，后再提交了一个 [压测时候的优化 Commits](https://github.com/link1st/gowebsocket/commit/42c989c0dbc45d302e672217f667db4688ab77f7) 修复了程序 map 并发读写的问题。


#### 问题二：

本项目的 chan 和 map 在用户断开连接的时候都是有处理的。

chan 和 map 中的数据如果不删除的话，肯定会导致内存溢出的，项目压测和线上的运行并没有发现内存溢出的现象。

下面我就来解释一下是怎么处理的

- 定时任务清理超时连接流程：

1、 task：定时清理超时连接，这里会关闭客户端 `client.Socket.Close()`，关闭了 **客户端连接的句柄**[client_manager.go](https://github.com/link1st/gowebsocket/blob/master/servers/websocket/client_manager.go) 332行

```
// 定时清理超时连接
func ClearTimeoutConnections() {
	currentTime := uint64(time.Now().Unix())

	clients := clientManager.GetClients()
	for client := range clients {
		if client.IsHeartbeatTimeout(currentTime) {
			fmt.Println("心跳时间超时 关闭连接", client.Addr, client.UserId, client.LoginTime, client.HeartbeatTime)

			client.Socket.Close()
		}
	}
}
```

2、 read：客户端连接句柄关闭，会触发 gowebsocket 如果读取客户端的数据失败 `c.Socket.ReadMessage()`，会返回一个 err 从而跳出循环，defer 延时函数就会 `close(c.Send)`，这里 **关闭 Client.Send chan**

[client.go](https://github.com/link1st/gowebsocket/blob/master/servers/websocket/client.go) 67行 read() 函数

```
// 读取客户端数据
func (c *Client) read() {
	...
	
	defer func() {
		close(c.Send)
	}()

	for {
		_, message, err := c.Socket.ReadMessage()
		if err != nil {

			return
		}

	   ...
	}
}
```


3、 write：Client.Send 关闭会触发 write 函数从 `message, ok := <-c.Send` 中读取数据关闭，从而跳出循环

4、 write：跳出循环会触发延时函数 `clientManager.Unregister <- c` 用户退出事件 和 `c.Socket.Close()` 这里 **关闭了客户端的连接句柄**

[client.go](https://github.com/link1st/gowebsocket/blob/master/servers/websocket/client.go) 94行 write() 函数

```
// 向客户端写数据
func (c *Client) write() {
	...

	defer func() {
		clientManager.Unregister <- c
		c.Socket.Close()
	}()

	for {
		select {
		case message, ok := <-c.Send:
			if !ok {
				// 发送数据错误 关闭连接

				return
			}
			...
		}
	}
}
```


5、 EventUnregister：用户退出事件，会删除 `ClientManager.Clients` map 中客户端的连接信息，如果用户登录了，会删除用户登录信息 `ClientManager.User` ，修改redis中 将用户状态改为下线，这里删除了 **ClientManager.Clients 客户端连接信息** 

[client_manager.go](https://github.com/link1st/gowebsocket/blob/master/servers/websocket/client_manager.go) 239行 EventUnregister() 函数

```
// 用户断开连接
func (manager *ClientManager) EventUnregister(client *Client) {
	manager.DelClients(client)

	// 删除用户连接
	userKey := GetUserKey(client.AppId, client.UserId)
	manager.DelUsers(userKey)
	
	...
}
```

**Comment by lemonash** [comment]
非常感谢你详细的解答，看来是我没看仔细。另外还有个小问题在task_init.go中，t := time.NewTimer(delay)后是不加个defer t.Stop()。
现在这个项目我觉得如果把具体的业务拆到几个微服务中去，前面的acc只负责接入和维护websocket连接，然后通过grpc和后面提供服务的微服务通讯，不知道这个想法对不对。

**Comment by link1st** [comment]
是的，应该在 **task_init.go** 中 `t := time.NewTimer(delay)` 后面添加 `defer t.Stop()`

acc只负责接入和维护websocket连接，然后通过grpc和后面提供服务的微服务通讯？是的

下面是推荐的架构图，acc 只负责接入、给连接的客户端发送数据，acc 对内应该用 grpc 和微服务通讯通讯。

[项目架构图](https://github.com/link1st/gowebsocket#4gowebsocket-%E9%A1%B9%E7%9B%AE)

**Comment by lemonash** [comment]
还有一个小问题，在发送消息的时候，上层调用SendMsg（client.go），如果发送失败，没有返回error的话，上层不知道，那这条消息就丢了。如果上层知道的话，可以让用户选择重发或取消。
另外在架构方面，如果选择彻底的微服务化的话，还是有很多情况要考虑，希望可以多多向你请教。

**Comment by link1st** [comment]
消息发送到acc服务，上层服务的任务就完成了，(上层服务)就可以认为这条数据已经发送成功了

acc 收到消息会首次尝试发送，如果发送不成功是否需要重试问题就需要看业务场景的需要了

1、本项目对数据要求不高，所以不需要重试，只发送一次消息 --  send 一次

2、对消息有一定要求 -- send 失败以后，重试几次间隔一段时间再 send

3、如果对数据要求比较高，acc 收到上层服务的数据就先需要存储起来，后续发送失败了以后需要重试、用户登录或者有心跳包的时候都检查是否有未发送的数据
