### ISSUE TITLE
android / ios 客户端怎么连你这个websocket呢

### ISSUE THREAD

**Issue by Rain168** [link1st/gowebsocket#70]

**Comment by link1st** [comment]
android
[A Journey to Implement WebSocket in Your Android App Using Scarlet](https://medium.com/sampingan-tech/a-journey-to-implement-web-socket-in-your-android-app-using-scarlet-4c400516d350)

IOS
[Getting Started With WebSockets in iOS](https://www.waldo.com/blog/getting-started-with-websockets-in-ios)
