### ISSUE TITLE
不能删除超时的连接

### ISSUE THREAD

**Issue by haowaiwai** [link1st/gowebsocket#71]
有几率出现，log如下，请问怎么解决
心跳时间超时 关闭连接 死循环输出

webSocket 建立连接: 192.168.128.1:32946
读取客户端数据 错误 192.168.128.1:32946 websocket: close 1005 (no status)
读取客户端数据 关闭send &{192.168.128.1:32946 0xc0005966e0 0xc0005110e0 0 1708586828 1708586828 0}
Client发送数据 关闭连接 192.168.128.1:32946 ok false
Client发送数据 defer &{192.168.128.1:32946 0xc0005966e0 0xc0005110e0 0 1708586828 1708586828 0}
EventRegister 用户建立连接 192.168.128.1:32946

心跳时间超时 关闭连接 192.168.128.1:32946 0 1708586828
心跳时间超时 关闭连接 192.168.128.1:32946 0 1708586828
心跳时间超时 关闭连接 192.168.128.1:32946 0 1708586828
心跳时间超时 关闭连接 192.168.128.1:32946 0 1708586828
心跳时间超时 关闭连接 192.168.128.1:32946 0 1708586828
心跳时间超时 关闭连接 192.168.128.1:32946 0 1708586828

**Comment by link1st** [comment]
1、读取客户端数据错误， `fmt.Println("读取客户端数据 错误", c.Addr, err)` 跳出 for 循环
2、`defer func` 处理退出程序，触发  `close(c.Send)` 关闭协程
```
// 读取客户端数据
func (c *Client) read() {
	defer func() {
		fmt.Println("读取客户端数据 关闭send", c)
		close(c.Send)
	}()

	for {
		_, message, err := c.Socket.ReadMessage()
		if err != nil {
			fmt.Println("读取客户端数据 错误", c.Addr, err)
			return
		}
	}
}
```
3、send 协程关闭，触发 `ok = false` ,打印 `fmt.Println("Client发送数据 关闭连接", c.Addr, "ok", ok)`
4、`defer func` 函数处理退出程序
> `clientManager.Unregister <- c` 处理客户端退出
> `c.Socket.Close()` 关闭 socket 
> 打印日志 `fmt.Println("Client发送数据 defer", c)`
```
// 向客户端写数据
func (c *Client) write() {
	defer func() {
		clientManager.Unregister <- c
		c.Socket.Close()
		fmt.Println("Client发送数据 defer", c)
	}()
	for {
		select {
		case message, ok := <-c.Send:
			if !ok {
				// 发送数据错误 关闭连接
				fmt.Println("Client发送数据 关闭连接", c.Addr, "ok", ok)
				return
			}
		}
	}
}
```
5、`manager.EventUnregister(conn)` 断开连接处理事件，没有打印断开连接的日志，需要检查为什么没有执行到这一步骤
> 调用 `/system/state` 检查 chanRegisterLen 未处理连接事件数 是否处理慢
```
	manager.DelClients(client)
	// 删除用户连接
	deleteResult := manager.DelUsers(client)

	fmt.Println("EventUnregister 用户断开连接", client.Addr, client.AppId, client.UserId)
```

6、定时清理超时连接
> 循环 `clientManager.GetClients()` ，步骤五应该会清除这个连接，需要检查第五步未执行的原因
```
// 定时清理超时连接
func ClearTimeoutConnections() {
	currentTime := uint64(time.Now().Unix())
	clients := clientManager.GetClients()
	for client := range clients {
		if client.IsHeartbeatTimeout(currentTime) {
			fmt.Println("心跳时间超时 关闭连接", client.Addr, client.UserId, client.LoginTime, client.HeartbeatTime)
			client.Socket.Close()
		}
	}
}
```

**Comment by haowaiwai** [comment]
你好，我分析：

断开连接事件处理快，已经处理完了，才处理连接事件，我不太清楚为什么会出现这种情况

断开连接事件处理的时候，因为没有连接，所以return了，没有EventUnregister 用户断开连接这行打印
```
// 用户断开连接
func (manager *ClientManager) EventUnregister(client *Client) {
        manager.DelClients(client)

        // 删除用户连接
        deleteResult := manager.DelUsers(client)
        if deleteResult == false {
                // 不是当前连接的客户端

                return
        }
}
```

**Comment by link1st** [comment]
建立连接事件和 断开连接事件，都是通过 chan 进行异步处理的，如果系统处理有延时，就会导致消息顺序有问题
解决方案，可以将 EventRegister、EventLogin 事件修改为同步的，

```
func wsPage(w http.ResponseWriter, req *http.Request) {

	// 用户连接事件
	// clientManager.Register <- client

	clientManager.EventRegister(client)
}

```
```
// 用户登录
func LoginController(client *Client, seq string, message []byte) (code uint32, msg string, data interface{}) {
	// clientManager.Login <- login
	clientManager.EventLogin(login)
	fmt.Println("用户登录 成功", seq, client.Addr, request.UserId)
	return
}
```

**Comment by haowaiwai** [comment]
谢谢，我试试效果

**Comment by 520aky** [comment]
```
func (c *Client) write() {
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("write panic:", r)
        }
        clientManager.Unregister <- c
        _ = c.Socket.Close()
        fmt.Println("writer exit:", c.Addr)
    }()

    const writeWait = 10 * time.Second

    for msg := range c.Send { // 通道关闭 -> 自动退出
        _ = c.Socket.SetWriteDeadline(time.Now().Add(writeWait))
        if err := c.Socket.WriteMessage(websocket.TextMessage, msg); err != nil {
            fmt.Println("write err:", c.Addr, err)
            return
        }
    } 
}
```

write这样写就可以解决问题了
