### ISSUE TITLE
client_manager.go   文件的 GetUserKeys  方法 不需要加锁，并优化初始化值

### ISSUE THREAD

**Issue by zhezhizhuo** [link1st/gowebsocket#76]
func (manager *ClientManager) GetUserKeys() (userKeys []string) {
	userKeys = make([]string, 0)
	manager.UserLock.RLock()
	defer manager.UserLock.RUnlock()
	for key := range manager.Users {
		userKeys = append(userKeys, key)
	}
	return
}

修改后
// GetUserKeys 获取用户的key
func (manager *ClientManager) GetUserKeys() (userKeys []string) {
	userKeys = make([]string, len(manager.Users))

	// todo  这里只是获取string key值 不需要加锁
	//manager.UserLock.RLock()
	//defer manager.UserLock.RUnlock()

	for key := range manager.Users {
		userKeys = append(userKeys, key)
	}
	return
}

**Comment by link1st** [comment]
已经更新
> make([]string, 0, len(manager.Users)), 只设置 cap，append 可以从 index 0 开始添加
```
// GetUserKeys 获取用户的key
func (manager *ClientManager) GetUserKeys() (userKeys []string) {
	userKeys = make([]string, 0, len(manager.Users))
	for key := range manager.Users {
		userKeys = append(userKeys, key)
	}
	return
}
```
