### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by ghost** [link1st/gowebsocket#9]
非常好的项目 根据这个做了进一步的开发 但是有个问题 想请教一下 
将您目前的代码修改为 用户登录后再登录之后 关闭旧的登录 但是由于EventUnregister 执行的不及时导致 AddUser 之后被删除;
也就是说 用户在A设备上登录 然后又去B设备登录 登录B设备的时候想将A设备踢下线
原本想的流程为:将设备A踢下线manager.Socket.Close() (这里会触发 client.write 的defer 方法 在这里往管道`clientManager.Unregister`里面写入了数据; 之后执行 manager.AddUser() 新的用户

但是实际执行的流程却是 先增加后删除 新登录的 和旧的 都被删除了 不知道我这样表达能不能让您明白

原本在A设备登录的时候 manager.User 大概是 `map[1:0xc000035b00]` 但是B登录后 就变空了

最后 希望您留个赞助码什么的 对目前的项目帮助挺大的!

**Comment by link1st** [comment]
表达的很清楚，如果用户先登录 AddUser，由于后收到 EventUnregister 删除用户的事件，就会把之前登录的用户给删除了

这里需要对代码进行改造一下，删除用户的时候传入`client *Client` 然后比较一下需要删除的客户端地址和`ClientManager.Users` 中的客户端地址比较一下是否是一致的，一致再删除

解决方法 [删除用户判断客户端地址是否一致](https://github.com/link1st/gowebsocket/commit/cec491b93479262e163483e2f03885d624f9de62)

由于这个系统设计的时候(一个AppId **登录的平台Id app/web/ios** )只能有一个登录，同一个平台的登录可能需要做一下单点登录，不同平台可以用不同的AppId区分一下，这样就能实现多端登录

赞助的话可以算了，我比较喜欢一起分享交流学习的经验(建立交流群还在考虑中)~

**Comment by ghost** [comment]
好 等建群ing
